### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by wellwelwel** [testdouble/quibble#107]
First of all, thank you for this project!

It's amazing, I could easily create a mock for both **ESM** and **CJS** with the same code, by just changing from `quibble()` to `quibble.esm()` ✨

Also, it's really great that we can use **quibble** with the native **Node.js** **CLI** (`node ./my-file.js`) 🚀

---

## About Typings

I would like to ask if a _PR_ introducing typings (an `index.d.ts`, for example) would be welcome 🙋🏻‍♂️

---

## Why

To use **quibble** in a **TypeScript** project, first I need to create an `any` for it by creating a `quibble.d.ts` in the same level as the `src`, for example:

```ts
declare module 'quibble' {
  const quibble: any;
  export default quibble;
}
```

**Comment by wellwelwel** [comment]
> Creating the typings would be my way of saying thank you

It took me more than five hours to achieve this result without success, until I went to the **quibble** and my problem was solved in less than five minutes.

<img width="431" alt="Screenshot 2024-02-28 at 06 02 18" src="https://github.com/testdouble/quibble/assets/46850407/c087574f-54e8-4196-a3a7-ec844d1d32e7">

**Comment by searls** [comment]
Thanks for the note. I don't use typescript, but if someone was willing to take on the task of doing it well I'd appreciate it. I'd probably point them to [testdouble.js](https://github.com/testdouble/testdouble.js), where the community has provided a typing file that's been iterated on over time, as a starting point
