### ISSUE TITLE
Node 8.7.0 throws error with quibble

### ISSUE THREAD

**Issue by marchaos** [testdouble/quibble#15]
Pretty sure you're aware of this issue. Error thrown is: 

TypeError: Module._cache.hasOwnProperty is not a function

**Comment by searls** [comment]
I was aware of it but only insofar as we couldn't replicate it and updating dependencies fixed it. https://github.com/testdouble/quibble/issues/14

Can you please give a reproducible example?

**Comment by marchaos** [comment]
Can confirm - Old version to testdouble :)
