### ISSUE TITLE
Detect that `require(../lib/dep.js)` and `require(../lib/dep)` load the same module

### ISSUE THREAD

**Issue by erikerikson** [testdouble/quibble#16]
bone-headed move on my part but burned some time on the equivalent by result but differently stated requirement statements.

**Comment by searls** [comment]
Ooh, does it not do this? That's not good

**Comment by searls** [comment]
Hey Erik, could you provide a little example to demonstrate this? I'm struggling to reproduce

**Comment by erikerikson** [comment]
See https://github.com/erikerikson/quibble-test for a reproduction.

In the dependent, I use `require('./dependency')`: https://github.com/erikerikson/quibble-test/blob/master/dependent.js#L1
In the "spec", I use `quibble('./dependency.js', [...]`: https://github.com/erikerikson/quibble-test/blob/master/dependent.spec.js#L8

This could probably be simpler but I found the issue investigating unexpected behavior.

Thanks for taking a look!

**Comment by searls** [comment]
Thanks a lot for the reproduction, Erik. I agree this really shouldn't behave like you're describing and I'll look more closely soon.

**Comment by erikerikson** [comment]
might be worth your time looking at https://github.com/nodejs/node-v0.x-archive/blob/master/lib/module.js#L124

**Comment by searls** [comment]
Ok, I've got your reproduce case workign.

**Comment by searls** [comment]
Hey Erik, I spent this morning converting the lib to a compilation-less ES5 + standard combo. If this makes the codebase more approachable for you to attempt a PR, that'd be great. Otherwise I'll look at this soon

**Comment by searls** [comment]
Landed in 0.5.3, along with half a dozen other fixes for edge cases I hadn't thought about before.

**Comment by erikerikson** [comment]
Thanks @searls, much appreciated!
