### ISSUE TITLE
doesn't work with jest :-( 

### ISSUE THREAD

**Issue by lgandecki** [testdouble/quibble#23]
I've tried with multiple combinations of nodejs (from 6+) and jest (some ancient ones). Couldn't pin point where in jest it stopped working, so started digging in quibble.

```javascript
    return _.flow([
      _.invokeMap('getFileName'),
      _.compact,
      _.reject(function (f) {
        return includeGlobalIgnores && _.includes(f, ignoredCallerFiles)
      }),
      _.filter(path.isAbsolute),
      _.find(function (f) {
        return f !== currentFile
      })
    ])(e.stack)
```

in jest this doesn't work properly ,and returns garbage like:  /Users/lukaszgandecki/projects/prototypes/testdoubleweirdness/node_modules/jest-runtime/build/index.js

When I remove the _.filter(path.isAbsolute) I can see the file that is the caller, but it's relative, not absolute. Mocha shows it as

 /Users/lukaszgandecki/projects/prototypes/testdoubleweirdness/lib/abc.js

and jest shows it as

lib/abc.js

I tried to hack around it, but I failed, and I need to get out of the office and get some sleep :-) (Abu Dhabi zone here)

Any ideas? 

To reproduce, use your example here in this repo, copy & paste our helper.js file into zoo-spec.js like so:

```javascript

global.expect = require('chai').expect
global.context = describe
quibble = require('quibble')

beforeEach(function () {
  // Config a default response for quibbles (usually in a spec helper)
  quibble.config({
    defaultFakeCreator: function (path) {
      return function () { return 'a fake animal' }
    }
  })
})

afterEach(function () {
  quibble.reset()
})

quibble = require('quibble')

require('../../lib/zoo') // drop the zoo in the cache

describe('zoo', function () {
  var subject

  beforeEach(function () {
    quibble('../../lib/animals/bear') // return ->'a fake animal'; see helper.js
    quibble('../../lib/animals/lion', function () { return 'a fake lion' })

    subject = require('../../lib/zoo')
  })

  it('contains a fake animal', function () {
    expect(subject().animals).to.contain('a fake animal')
  })

  it('contains a fake lion', function () {
    expect(subject().animals).to.contain('a fake lion')
  })
})

```

and then install jest and change your scripts to

```javascript
    "test": "mocha -R spec --recursive test/lib/",
    "jestTest": "jest test/lib/zoo-spec.js",
```

to your example/package.json.
After that you can run mocha with npm test and jest with npm run jestTest, mocha will pass, jest will fail (the mock won't happen, because of the wrongly returned caller)

**Comment by searls** [comment]
Closing -- After investigating how Jest works, it proved more appropriate to just build `td.replace` on top of `jest.mock`, which works as of testdouble@3.5.0 and testdouble-jest@1.0.1. More info here: https://github.com/testdouble/testdouble-jest 🎊
