### ISSUE TITLE
Is quibble only V8 compatible (not working in PhantomJS)?

### ISSUE THREAD

**Issue by bjarketrux** [testdouble/quibble#3]
I'm trying to execute unit test on our CI server using PhantomJS, but I get an error in `hackErrorStackToGetCallerFile()` with the following message: `phantomjs: TypeError: undefined is not an object (evaluating 'e.stack[0]')`.

It seems the implementation of `hackErrorStackToGetCallerFile()` is relying on a V8 specific implementation of `stack` on `Error`.

According to [Stack-Trace-API](https://github.com/v8/v8/wiki/Stack-Trace-API) the api is only for V8:

> The API described here is specific to V8 and is not supported by any other JavaScript implementations. Most implementations do provide an error.stack property but the format of the stack trace is likely to be different from the format described here.

We can get the stack in PhantomJS only by throwing an error [stack reference](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error/stack):

```
Error.prepareStackTrace = function(error, structuredStackTrace) {
    console.log("prepareStackTrace:", error, structuredStackTrace);
}

var ex = new Error();
console.log("Properties on ex:", Object.getOwnPropertyNames(ex));

try {
    throw(new Error());
}
catch(e) {
    console.log("Properties on e:", Object.getOwnPropertyNames(e));
    console.log("Typeof e.stack:", typeof e.stack);
    console.log("e.stack:", e.stack);
}
```

will produce the following output:

```
Properties on ex: 
Properties on e: line,sourceURL,stack
Typeof e.stack: string
e.stack: global code@phantomjs://code/ph.js:9:23
```

So no support for `prepareStackTrace` and `getFileName` and therefore the stack will be only a string. Can quibble in any way be updated to use this string instead of V8 specific `getFileName()`?

By the way we use Mocha tests with testdouble.js and execute them in PhantomJS (Meteor project). We do not use `td.replace(path, replacement)` as it does not work with meteor, so quibble should not actually be used.

Thanks

**Comment by clayne11** [comment]
`td.replace(path, replacement)` actually does work perfectly with Meteor. I'm using it in my project.

**Comment by bjarketrux** [comment]
But do you use the 'meteor test' command or 'mocha' CLI?
I found the latter to work, as it does not starting up the entire server to be able to write integration tests.
Either way it still looks like quibble is V8 only...

**Comment by searls** [comment]
Hey @bjarketrux sorry for missing this other issue, but quibble can't work with PhantomJS because it works by monkey-patching the Node.js built-in `Module` module's `_load` method, which PhantomJS lacks, as it does not implement a CommonJS-like module spec, and certainly not _that_ one.

If you're saying you use another commonJs-like module system in your JS code, quibble's semantics may be portable to it.
