### ISSUE TITLE
ESM support does not appear to work with "bare" imports

### ISSUE THREAD

**Issue by JaredReisinger** [testdouble/quibble#34]
This is my first time using quibble (testdouble, actually, but I think I've tracked the problem here), so it's quite possible that I'm misunderstanding something about the way things are supposed to work.  If I'm understanding correctly, however, there's something in the "bare specifier" import case that's not quite working.  I have a minimal repro at https://github.com/JaredReisinger/quibble-repro, where `npm run start` shows the normal, non-quibble behavior, and `npm run repro` shows the quibble-wrapped behavior.  As you can see, the quibble-replacement of the local import works as expected, but the quibble-replacement of "fs" (a bare specifier) does not.

This was repro'd on node 14.5.0.

##### `npm run start` _(no replacements are expected)_

```plain
> quibble-repro@0.0.1 start /home/jared/src/JaredReisinger/quibble-repro
> node ./index.mjs

This is main...
Apparently, replaceMe was not replaced!

from README:
------------
# quibble-repro

minimally reproduce a quibble replaceEsm problem

(If you see this from `npm run repro`, that's the problem!)
------------
```

##### `npm run repro` _(both replacements are expected, only the local one actually happens)_

```plain
> quibble-repro@0.0.1 repro /home/jared/src/JaredReisinger/quibble-repro
> node --loader=quibble ./repro.mjs

(node:5729) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

This is main...
a local import was properly replaced

from README:
------------
# quibble-repro

minimally reproduce a quibble replaceEsm problem

(If you see this from `npm run repro`, that's the problem!)
------------
```

Following the advice from [testdouble wiki's "Don't mock what you don't own"](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own) page, I might simply wrap the external/bare import with a local shim/facade so that I can replace the shim instead.  That feels a little "unnecessarily boilerplate-y" for my particular use-case, but it's doable.  Still, I wanted to pass this along just in case the repro _should_ be something that should work.

**Comment by searls** [comment]
cc/ @giltayar who actually understands this :)

**Comment by giltayar** [comment]
Wow. Thanks for the repro! I wonder if I tried it with a builtin module ("`fs`")... I'll look into it this evening.

**Comment by giltayar** [comment]
Working on it. You forgot to "await" the `quibble.esm`, but the bug still appears even after I fixed it.

**Comment by giltayar** [comment]
Uh, yeah. Quibble doesn't work with internal Node.js modules. And I forgot to update the documentation. I'll try and remove that limitation before I resort to fixing the documentation... :-)

**Comment by giltayar** [comment]
@JaredReisinger the problem was not with regular bare imports, but rather with internal modules ('fs', 'net', ...). 

I fixed this in a new PR (see above).

Note that your repro has a bug. Instead of:

```js
  quibble.esm("fs", {
    readFileSync: function (path) {
      console.log("using quibbled readFileSyns... yay!");
      return "Looks like 'fs' was replaced correctly.";
    },
  });
```

You should write: 

```js
  await quibble.esm("fs", undefined, {
    readFileSync: function (path) {
      console.log("using quibbled readFileSyns... yay!");
      return "Looks like 'fs' was replaced correctly.";
    },
  });
```

1. `quibble.esm` is async and so should be awaited.
2. `quibble.esm` accepts two mock parameters: the "named exports" and the "default export". Since you import the default export, then the third parameter should be the one you mock. The internal modules are unique in that they are both the same (the default export is an object that has properties with the same names as the named exports), so the more correct way to do this would be:

```js
  const fsExports = {
    readFileSync: function (path) {
      console.log("using quibbled readFileSyns... yay!");
      return "Looks like 'fs' was replaced correctly.";
    },
  }
  await quibble.esm("fs", fsExports, fsExports);
```

**Comment by JaredReisinger** [comment]
So, interestingly, I actually ran into this trying to mock `fs-extra`, not `fs`.  I'm glad you were able to dig into this, though, otherwise my next step was going to be learning all about the new node loader system!  😄

I may extend the repro to cover both cases (and fix the `await` on `quibble.esm`!) and see how it goes.

Thanks for the quick resolution!
