### ISSUE TITLE
Add documentation for replacing builtinModules and esm function's parameters

### ISSUE THREAD

**Issue by TimDaub** [testdouble/quibble#40]
[Here](https://github.com/testdouble/quibble/issues/34#issuecomment-654957764) @giltayar wrote that:

> quibble.esm accepts two mock parameters: the "named exports" and the "default export". Since you import the default export, then the third parameter should be the one you mock. The internal modules are unique in that they are both the same (the default export is an object that has properties with the same names as the named exports), so the more correct way to do this would be:

```js
 const fsExports = {
    readFileSync: function (path) {
      console.log("using quibbled readFileSyns... yay!");
      return "Looks like 'fs' was replaced correctly.";
    },
  }
  await quibble.esm("fs", fsExports, fsExports);
```

What I think was said implicitly, but is important to mention explicitly is that when you decide to use `quibble` either with the _first_ parameter (that is "named exports") or _second_ parameter (that is "default exports"), then for an internal it will 
take either "a named exports" or a "default exports" form!

Hence, it's important for internal modules to always use quibble as described above.

Anyways, if you want to add this to the README.md, I'm happy to write a few lines.

**Comment by giltayar** [comment]
@TimDaub you're right in that this text is confusing and unclear. I'll try and rewrite it this week, but if you want to take a stab at it, would love to see it

**Comment by giltayar** [comment]
@searls the PR @TimDaub wrote looks good!
