### ISSUE TITLE
quibble doesn't throw when file can't be found

### ISSUE THREAD

**Issue by TimDaub** [testdouble/quibble#64]
- node v14.19.1
- fantasy directoy exists
- ./fantasy/fantasy.mjs doesn't exist

```
// index.mjs
import quibble from "quibble";

const run = async () => {
  await quibble.esm("./fantasy/fantasy.mjs");
};
run().catch(console.log).then(console.log);
```

when you run `node index.mjs` it just returns `undefined`. My expectation is that it should throw.

**Comment by searls** [comment]
I don't think this is a bug. If you see [this test of non-ESM](https://github.com/testdouble/quibble/blob/main/test/lib/quibble.test.js#L63-L67), quibble has always supported faking non-existent paths

**Comment by TimDaub** [comment]
I found it quite confusing and it cost me some time only understanding that it wouldn't throw.

Maybe, would you be willing to allow the esm function to throw if a special input is passed. Or maybe a `safeEsm` function?

Otherwise, maybe making people more aware in the readme could help too.

**Comment by searls** [comment]
I understand your point, but because this is a mature/stable/low-config library I would not support a new option for branching behavior like this. Happy to look at a PR that warns replacing paths to non-existent files is supported, however
